# Generated by scripts/generate.py. Do not edit.
require_relative "transport"
module Robotomail
  class Client < Transport
    # Create an account.
    def create_signup(body)
      request("POST", "/signup", body: body, params: {}, file: nil)
    end
    # Check if an account slug is available.
    def check_slug_availability(params: {})
      request("GET", "/signup/check-slug", body: nil, params: params, file: nil)
    end
    # Get account stats.
    def get_account()
      request("GET", "/account", body: nil, params: {}, file: nil)
    end
    # Delete account permanently.
    def delete_account(body)
      request("DELETE", "/account", body: body, params: {}, file: nil)
    end
    # Send the welcome email.
    def send_welcome_email()
      request("POST", "/account/welcome", body: nil, params: {}, file: nil)
    end
    # Resolve post-verification target.
    def set_post_verify_target()
      request("POST", "/account/post-verify-target", body: nil, params: {}, file: nil)
    end
    # List API keys.
    def list_api_keys()
      request("GET", "/api-keys", body: nil, params: {}, file: nil)
    end
    # Create an API key.
    def create_api_key(body)
      request("POST", "/api-keys", body: body, params: {}, file: nil)
    end
    # Revoke an API key.
    def revoke_api_key(id)
      request("DELETE", "/api-keys/#{segment(id)}", body: nil, params: {}, file: nil)
    end
    # List mailboxes.
    def list_mailboxes()
      request("GET", "/mailboxes", body: nil, params: {}, file: nil)
    end
    # Create a mailbox.
    def create_mailbox(body)
      request("POST", "/mailboxes", body: body, params: {}, file: nil)
    end
    # Get a mailbox.
    def get_mailbox(id)
      request("GET", "/mailboxes/#{segment(id)}", body: nil, params: {}, file: nil)
    end
    # Update a mailbox.
    def update_mailbox(id, body)
      request("PATCH", "/mailboxes/#{segment(id)}", body: body, params: {}, file: nil)
    end
    # Delete a mailbox.
    def delete_mailbox(id)
      request("DELETE", "/mailboxes/#{segment(id)}", body: nil, params: {}, file: nil)
    end
    # List messages in a mailbox.
    def list_messages(id, params: {})
      request("GET", "/mailboxes/#{segment(id)}/messages", body: nil, params: params, file: nil)
    end
    # Send an email from a mailbox.
    def send_message(id, body)
      request("POST", "/mailboxes/#{segment(id)}/messages", body: body, params: {}, file: nil)
    end
    # Get a message.
    def get_message(id, msg_id)
      request("GET", "/mailboxes/#{segment(id)}/messages/#{segment(msg_id)}", body: nil, params: {}, file: nil)
    end
    # List threads in a mailbox.
    def list_threads(id)
      request("GET", "/mailboxes/#{segment(id)}/threads", body: nil, params: {}, file: nil)
    end
    # Get a thread with its messages.
    def get_thread(id, tid)
      request("GET", "/mailboxes/#{segment(id)}/threads/#{segment(tid)}", body: nil, params: {}, file: nil)
    end
    # Upload an attachment.
    def upload_attachment(file)
      request("POST", "/attachments", body: nil, params: {}, file: file)
    end
    # Get an attachment download URL.
    def download_attachment(id)
      request("GET", "/attachments/#{segment(id)}", body: nil, params: {}, file: nil)
    end
    # Delete an attachment.
    def delete_attachment(id)
      request("DELETE", "/attachments/#{segment(id)}", body: nil, params: {}, file: nil)
    end
    # List custom domains.
    def list_domains()
      request("GET", "/domains", body: nil, params: {}, file: nil)
    end
    # Add a custom domain.
    def create_domain(body)
      request("POST", "/domains", body: body, params: {}, file: nil)
    end
    # Get a domain and its DNS records.
    def get_domain(id)
      request("GET", "/domains/#{segment(id)}", body: nil, params: {}, file: nil)
    end
    # Delete a domain.
    def delete_domain(id)
      request("DELETE", "/domains/#{segment(id)}", body: nil, params: {}, file: nil)
    end
    # Trigger domain verification.
    def verify_domain(id)
      request("POST", "/domains/#{segment(id)}/verify", body: nil, params: {}, file: nil)
    end
    # List webhooks.
    def list_webhooks()
      request("GET", "/webhooks", body: nil, params: {}, file: nil)
    end
    # Create a webhook.
    def create_webhook(body)
      request("POST", "/webhooks", body: body, params: {}, file: nil)
    end
    # Get a webhook.
    def get_webhook(id)
      request("GET", "/webhooks/#{segment(id)}", body: nil, params: {}, file: nil)
    end
    # Update a webhook.
    def update_webhook(id, body)
      request("PATCH", "/webhooks/#{segment(id)}", body: body, params: {}, file: nil)
    end
    # Delete a webhook.
    def delete_webhook(id)
      request("DELETE", "/webhooks/#{segment(id)}", body: nil, params: {}, file: nil)
    end
    # List webhook deliveries.
    def list_webhook_deliveries(id)
      request("GET", "/webhooks/#{segment(id)}/deliveries", body: nil, params: {}, file: nil)
    end
    # Stream inbox events over SSE.
    def stream_events(params: {})
      stream(params)
    end
    # List suppressed addresses.
    def list_suppressions()
      request("GET", "/suppressions", body: nil, params: {}, file: nil)
    end
    # Suppress an address.
    def create_suppression(body)
      request("POST", "/suppressions", body: body, params: {}, file: nil)
    end
    # Remove a suppression entry.
    def delete_suppression(id)
      request("DELETE", "/suppressions/#{segment(id)}", body: nil, params: {}, file: nil)
    end
    # Start a plan upgrade.
    def create_upgrade_checkout(body)
      request("POST", "/billing/upgrade", body: body, params: {}, file: nil)
    end
    # Resend the email verification link.
    def resend_verification_email(body)
      request("POST", "/auth/resend-verification", body: body, params: {}, file: nil)
    end
    # Contact support.
    def submit_support_ticket(body)
      request("POST", "/support", body: body, params: {}, file: nil)
    end
  end
end
